-- glxt-api 存储过程配置能力手工DDL
-- 执行前请按目标数据库方言调整字段类型和注释语法。

-- API_SQL_INTERFACE.TYPE:
--   1 = SQL查询
--   2 = 存储过程

ALTER TABLE API_SQL_INTERFACE ADD PROCEDURE_NAME VARCHAR2(256);

COMMENT ON COLUMN API_SQL_INTERFACE.PROCEDURE_NAME IS '存储过程名称，支持SCHEMA.PKG.PROC或PKG.PROC';

ALTER TABLE API_SQL_INTERFACE_PARAM ADD DIRECTION NUMBER(1);
ALTER TABLE API_SQL_INTERFACE_PARAM ADD JDBC_TYPE VARCHAR2(32);
ALTER TABLE API_SQL_INTERFACE_PARAM ADD ORDER_NO NUMBER(10);

COMMENT ON COLUMN API_SQL_INTERFACE_PARAM.DIRECTION IS '存储过程参数方向：1-IN，2-OUT，3-INOUT';
COMMENT ON COLUMN API_SQL_INTERFACE_PARAM.JDBC_TYPE IS '存储过程JDBC类型：VARCHAR/INTEGER/BIGINT/DECIMAL/DATE/TIMESTAMP/CURSOR';
COMMENT ON COLUMN API_SQL_INTERFACE_PARAM.ORDER_NO IS '存储过程参数绑定顺序，从1开始';
